import assert from 'node:assert/strict';
import { checkCanonical, checkSitemap, canonicalMap } from './canonical-validation.mjs';
const fail = message => { throw new Error(message); };
checkCanonical('gcse/index.html', '<link rel="canonical" href="https://www.ukonlinetuition.co.uk/services-4">', fail);
assert.throws(() => checkCanonical('gcse/index.html', '<link rel="canonical" href="https://www.ukonlinetuition.co.uk/gcse/">', fail), /mapping/);
assert.throws(() => checkCanonical('404.html', '<link rel="canonical" href="https://www.ukonlinetuition.co.uk/404/">', fail), /invent/);
checkCanonical('404.html', '', fail);
const canonicalUrls = [...new Set(Object.values(canonicalMap).map(e => e.url))];
checkSitemap(canonicalUrls.map(url => `<loc>${url}</loc>`).join(''), fail);
assert.throws(() => checkSitemap(canonicalUrls.map(url => `<loc>${url}</loc>`).join('') + `<loc>${canonicalUrls[0]}</loc>`, fail), /sitemap/);
assert.throws(() => checkSitemap('<loc>https://www.ukonlinetuition.co.uk/gcse/</loc>', fail), /sitemap/);
console.log('PASS: canonical and sitemap regression fixtures');
